apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  # this lables are replicaset labels
  labels:
    project: roboshop
    purpose: rs-demo
    tier: frontend
    component: frontend
spec:
  replicas: 20
  selector:
      # using this lables replicaset will select the pods.
    matchLabels:
      project: roboshop
      purpose: rs-demo
      tier: frontend
      component: frontend
      # this is pod definiton pod is subset of replicaset
  template:
    metadata:
      labels:
        project: roboshop
        purpose: rs-demo
        tier: frontend
        component: frontend
    spec:
      containers:
      - name: nginx
        image: nginx
