apiVersion: v1
kind: Pod
metadata:
  name: resource
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        #soft limit
        memory: "64Mi" 
        cpu: "200m" 
        #hard limit 
      limits:
        memory: "128Mi"  
        cpu: "150m"  